[build]
builder = "nixpacks"
buildCommand = "cd worker && npm install && npx prisma generate --schema=../prisma/schema.prisma"

[deploy]
startCommand = "cd worker && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
